version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.4
  - dependency-name: org.springframework:spring-beans
    versions:
    - 5.3.5
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.5
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.5
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.5
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.5
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.eclipse.jetty:apache-jsp
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-security
    versions:
    - 11.0.0
    - 11.0.1
